### ISSUE TITLE
OSX 10.15.4 fail to compile with QT 5.14.2

### ISSUE THREAD

**Issue by remixmabix** [rncbc/qjackctl#94]
![image](https://user-images.githubusercontent.com/5531093/81783399-8f4b4b80-94fb-11ea-9dd4-9cb95da2f5b9.png)

checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required

**Comment by rncbc** [comment]
check `config.log` for clues

**Comment by remixmabix** [comment]
Here is the error :

conftest.c:16:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by remixmabix** [comment]
Ok solved by switching to gcc-9 instead of the currrent clang Apple compiler.

=>

brew install gcc@9

cd /usr/local/bin

ln -s c++-9 c++
ln -s cpp-9 cpp
ln -s g++-9 g++
ln -s gcc-9 gcc
ln -s gcc-ar-9 gcc-ar
ln -s gcc-nm-9 gcc-nm
ln -s gcc-ranlib-9 gcc-ranlib
ln -s gcov-9 gcov
ln -s gcov-dump-9 gcov-dump
ln -s gcov-tool-9 gcov-tool
ln -s x86_64-apple-darwin19-c++-9 x86_64-apple-darwin19-c++
ln -s x86_64-apple-darwin19-g++-9 x86_64-apple-darwin19-g++
ln -s x86_64-apple-darwin19-gcc-9 x86_64-apple-darwin19-gcc
ln -s x86_64-apple-darwin19-gcc-ar-9 x86_64-apple-darwin19-gcc-ar
ln -s x86_64-apple-darwin19-gcc-nm-9 x86_64-apple-darwin19-gcc-nm
ln -s x86_64-apple-darwin19-gcc-ranlib-9 x86_64-apple-darwin19-gcc-ranlib
ln -s x86_64-apple-darwin19-gfortran-9 x86_64-apple-darwin19-gfortran

export PKG_CONFIG_PATH="/usr/local/lib:/usr/local/lib/pkgconfig"
export PATH="/usr/local/bin:$PATH"

Good luck

**Comment by noahhorn** [comment]
I ran into this issue as well while compiling qjackctl on a standard installation of macOS Catalina. I'm posting my work below in case it's helpful to anyone else. Since <a href="https://brew.sh/">Homebrew</a> has qjackctl I would definitely recommend just running <code>brew install qjackctl</code> on macOS instead of compiling from source if possible. It took me over an hour of troubleshooting to compile from source.

First error: <code>checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required</code>
<code>brew install qt</code>, <code>brew upgrade qt</code>, <code>brew link --force qt55</code> etc. did not solve this.
Eventually I got past this with <code>./configure CXXFLAGS='-std=c++11'</code> after discovering <a href="https://github.com/rncbc/qjackctl/issues/20">issue #20</a>.

Next error: <code>checking for JACK... no</code>
<code>configure: error: *** JACK library not found.</code>
I did all kinds of work to try to solve this. There was the following message directly preceding this error,
<code>checking for main in -lX11... no</code>
<code>checking for main in -lXext... no</code>
and I solved that by running <code>./configure CXXFLAGS='-std=c++11' LDFLAGS=-L/opt/X11/lib</code>, but that still did not solve the JACK issue. <code>brew install jack</code> succeeded but did not help. Per this <a href="https://askubuntu.com/questions/846374/qtjackctl-configure-returns-jack-library-not-found">askubuntu.com question</a>, I tried installing <code>libjack-dev</code> and <code>libjack-jackd2-dev</code>, but that didn't help. I tried variants on <code>./configure CXXFLAGS='-std=c++11' --with-jack=/usr/local/include/jack</code> without success. Eventually, combing through every configure & make file, in <code>CMakeLists.txt</code> I discovered a reference to pkg-config. I ran <code>brew install pkg-config</code>. Voila!!! It worked!

Summary for compiling from source on macOS Catalina, according to my experience:
<ul>
<li>Open Terminal and install Command Line Tools if you need to: <code>xcode-select --install</code>
<li>Download and install <a href="https://brew.sh/">Homebrew</a>
<li>Run <code>brew install pkg-config</code>
<li>Navigate to where you downloaded the source code, and run <code>./configure CXXFLAGS='-std=c++11' LDFLAGS=-L/opt/X11/lib</code>
</ul>

It would be really nice if the configure script could account for these two needs (pkg-config and fixing the Qt error with the right GCC version) with suggested fixes, instead of leaving macOS users wondering what to do.

**Comment by rncbc** [comment]
please propose a PR instead...

or you could try the cmake build system, while not official, it's there lurking as an alternative to autoconf (configure) for the ones that feel it's one better option, specially for non-GNU/Linux platforms...

byee

ps. personally, I have no plans to test something on anything that comes from the bitten-fruit corp. ever ;)
